- name: Hots Info
  hosts: all
  collections:
  - wenerme.alpine
  gather_facts: true
  tasks:
  - include_role:
      name: alpine
      tasks_from: ensure-python
    when: ansible_os_family == "Alpine"
  - import_role:
      name: alpine
      tasks_from: host-info
