- name: SSH Copy ID
  hosts: all
  vars_prompt:
    - name: ssh_pub_key_file
      prompt: "Where is your ssh pub key file?"
      private: no
      default: "{{ lookup('env','HOME') + '/.ssh/id_rsa.pub' }}"
    - name: remote_user
      promot: "Which user you want to add to?"
      private: no
      default: "{{ansible_user|default('admin')}}"

  tasks:
  - name: Set authorized key taken from file
    become: "{{remote_user != ansible_user}}"
    authorized_key:
      user: "{{remote_user}}"
      state: present
      key: "{{ lookup('file', ssh_pub_key_file) }}"
