- name: get alpine-release
  slurp:
    src: "/etc/alpine-release"
  register: slurp_result

- name: set version
  set_fact:
    alpine_version: "{{slurp_result.content | b64decode | regex_search('^[0-9]+[.][0-9]+')}}"
    alpine_major_version: "{{slurp_result.content | b64decode | regex_search('^[0-9]+[.][0-9]+')}}"
    alpine_full_version: "{{slurp_result.content | b64decode | regex_search('^[^\n\r]+')}}"

- name: debug alpine-preset
  debug:
    msg:
    - "Alpine Full Version: {{alpine_full_version}}"
    - "Alpine Major Version: {{alpine_major_version}}"
  tags:
  - debug
