- include_tasks: alpine-update.yaml
- name: apk version
  raw: apk version
  register: raw_result
  changed_when: no
- name: apk upgrade detail
  debug:
    var: raw_result.stdout_lines
  changed_when: no
- name: apk upgrade
  become: true
  raw: apk upgrade
  when: raw_result.stdout_lines | length > 1
