- import_tasks: apk-update.yaml
- name: apk version
  raw: apk version
  register: raw_result
  changed_when: no
- name: apk upgrade detail
  debug:
    var: raw_result.stdout_lines
  changed_when: no

- name: set upgradable count
  set_fact:
    apk_upgradable_count: "{{(raw_result.stdout_lines|length) - 1|int}}"
