- name: avahi | install
  become: true
  package:
    name: "{{item}}"
    state: present
  loop:
  - avahi
  - avahi-tools

# dependency
- import_tasks: dbus-service.yaml

- name: avahi | start
  become: true
  service:
    name: avahi-daemon
    state: started
    enabled: true
