- name: dbus | install
  become: true
  apk:
    name: "{{item}}"
  loop:
  - dbus
  # - dbus-openrc

# 可能存在已失效的 /var/run/dbus.pid 导致启动失败
- name: dbus | fix pid
  become: true
  shell: |
    [ -e /var/run/dbus.pid ] && [ ! -d "/proc/$(cat /var/run/dbus.pid )" ] && rm /var/run/dbus.pid
  failed_when: false

- name: dbus | start
  become: true
  service:
    name: dbus
    state: started
    enabled: true
