- name: dnsmasq conf sync
  include_role:
    name: alpine
    tasks_from: service-conf-sync
  vars:
    service_name: dnsmasq
    service_conf_dest_path: /etc/dnsmasq.conf
    service_conf_file: dnsmasq.conf
    service_notify_type: restart

- name: resolv dnsmasq conf sync
  include_role:
    name: alpine
    tasks_from: service-conf-sync
  vars:
    service_name: dnsmasq
    service_conf_dest_path: /etc/resolv.dnsmasq.conf
    service_conf_file: resolv.conf
    service_notify_type: restart

- name: dnsmasq.d conf sync
  include_role:
    name: alpine
    tasks_from: service-conf-sync
  vars:
    service_name: dnsmasq
    service_conf_dest_path: /etc/dnsmasq.d
    service_conf_file: dnsmasq.d
    service_conf_delete: true
    service_notify_type: restart
