- name: install dnsmasq
  become: true
  apk:
    name: dnsmasq
  when: dnsmasq_dnssec is undefined

# dnsmasq with dnssec support - conflict with dnsmasq
- name: install dnsmasq-dnssec (optional)
  become: true
  apk:
    name: dnsmasq-dnssec
  when: dnsmasq_dnssec is defined

- name: sync dnsmasq conf
  include_tasks: dnsmasq-conf-sync.yaml

- name: start dnsmasq service
  become: true
  service:
    name: dnsmasq
    state: started

- name: enable dnsmasq service
  become: true
  service:
    name: dnsmasq
    enabled: true
