- name: install dnsmasq
  apk:
    name: dnsmasq

- name: sync conf
  include_tasks: dnsmasq-conf-sync.yaml

- name: start dnsmasq service
  become: true
  service:
    name: dnsmasq
    state: started

- name: enable dnsmasq service
  become: true
  service:
    name: dnsmasq
    enabled: true
