- name: install docker
  become: true
  apk:
    name: "{{item}}"
  loop:
  - docker
  # for ansbile docker module
  - py3-dockerpty

- name: mkdir /etc/docker
  become: true
  file:
    path: /etc/docker
    state: directory
- name: set docker mirror {{docker_mirror}}
  become: true
  copy:
      dest: /etc/docker/daemon.json
      content: '{ "registry-mirrors": ["{{docker_mirror}}"] }'
  notify: docker-restart
- name: start docker on bootstrap
  become: true
  service:
    name: docker
    enabled: yes

- name: add admin to docker group
  become: true
  user:
    name: admin
    groups: docker
    append: yes
