- name: install docker
  become: true
  package:
    name: "{{item}}"
    state: present
  loop:
  - docker
  # for ansbile docker module
  - py3-dockerpty

- name: add admin to docker group
  become: true
  user:
    name: admin
    groups:
    - docker
    append: yes
