- import_tasks: docker-install.yaml

- name: mkdir /etc/docker
  become: true
  file:
    path: /etc/docker
    state: directory

- name: set docker mirror {{docker_mirror}}
  become: true
  copy:
      dest: /etc/docker/daemon.json
      # fixme should not override whole json
      content: '{ "registry-mirrors": ["{{docker_mirror}}"] }'
  notify: docker-restart

- name: start docker on bootstrap
  become: true
  service:
    name: docker
    enabled: yes
