# setup gateway interface

- name: install packages
  become: true
  apk:
    name: '{{item}}'
  loop:
  - iproute2
  - bridge
  - iptables


- name: setup interface
  set_fact:
    gateway_interface: "{{gateway_interface|default('eth0')}}"
    gateway_source: "{{gateway_source|default('0.0.0.0/0')}}"
    gateway_persist: "{{gateway_persist|default(true)}}"

- name: sysctl conf
  become: true
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    state: present
  loop:
    - {name: net.ipv4.ip_forward, value: 1}

# iptables -I FORWARD -i eth0 -j ACCEPT
# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

- name: enable forward
  become: true
  iptables:
    in_interface: "{{gateway_interface}}"
    source: "{{gateway_source}}"
    action: insert
    chain: FORWARD
    jump: ACCEPT

- name: enable nat
  become: true
  iptables:
    out_interface: "{{gateway_interface}}"
    source: "{{gateway_source}}"
    action: append
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE

- name: persist forward conf
  become: true
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{gateway_interface}}"
    option: post-up
    value: iptables -I FORWARD -i {{gateway_interface}} -s {{gateway_source}} -j ACCEPT
    state: present
  when: gateway_persist

- name: persist nat conf
  become: true
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{gateway_interface}}"
    option: post-up
    value: iptables -t nat -A POSTROUTING -o {{gateway_interface}} -s {{gateway_source}} -j MASQUERADE
    state: present
  when: gateway_persist
