- name: install qemu
  apk:
    name: "{{item}}"
  loop:
  - qemu
  - qemu-system-x86_64
  - qemu-ui-curses
  - qemu-img

# - name: create qemu user
#   user:
# sudo adduser -S qemu -D -s /sbin/nologin
