- name: set hostname
  become: true
  hostname:
    name: "{{hostname|default(inventory_hostname)}}"
    use: alpine

- name: set /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: '{{item}} {{hostname|default(inventory_hostname)}}'
    state: present
  loop:
  - "127.0.0.1"
  - "::"
