- name: check exists
  stat:
    path: /etc/update-extlinux.conf
  register: stat

- name: check kernel params
  become: true
  lineinfile:
    path: /etc/update-extlinux.conf
    backrefs: yes
    regexp: '^default_kernel_opts="[^"]*cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory[^"]*"'
    state: absent
  check_mode: yes
  register: lineinfile
  changed_when: false
  when: stat.stat.exists

- name: add cgroup kernel params
  become: true
  lineinfile:
    path: /etc/update-extlinux.conf
    backrefs: yes
    regexp: '^default_kernel_opts="([^""]*)"'
    line: 'default_kernel_opts="\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"'
  when: lineinfile.found is defined and not lineinfile.found

- name: install basic package
  become: true
  apk:
    name: '{{item}}'
  loop:
  - socat
  - iproute2
  - iptables

- import_tasks: machine-id.yaml
