# /etc/rancher/k3s/registries.yaml
# https://rancher.com/docs/k3s/latest/en/installation/private-registry/

- name: k3s | registries.yaml
  become: true
  file:
    path: /etc/rancher/k3s/registries.yaml
    state: file

- name: k3s | inline registry
  become: true
  copy:
    dest: /etc/rancher/k3s/registries.yaml
    content: "{{k3s_registry_inline | to_yaml}}"
  when:
  - k3s_registry_inline is defined
  - k3s_registry_inline is mapping

- name: k3s | inline registry
  become: true
  copy:
    dest: /etc/rancher/k3s/registries.yaml
    content: "{{k3s_registry_inline}}"
  when:
  - k3s_registry_inline is defined
  - k3s_registry_inline is string
