# create_uninstall https://github.com/rancher/k3s/blob/master/install.sh#L583

- name: k3s | remove state
  become: true
  file:
    path: "{{item}}"
    state: absent
  loop:
  - /etc/rancher/k3s
  - /var/lib/kubelet
  - /var/lib/rancher/k3s
  - /run/k3s
  - /run/flannel

