# create_killall https://github.com/rancher/k3s/blob/master/install.sh#L497

- name: k3s | stop service
  become: true
  service:
    name: k3s
    state: stopped
    enabled: false

- name: k3s | stop docker
  become: true
  service:
    name: docker
    state: stopped
    enabled: false

- name: k3s | killall k3s
  become: true
  shell: killall -q k3s || true

- name: k3s | kill shims
  become: true
  shell: |
    pschildren() {
        ps -e -o ppid= -o pid= | \
        sed -e 's/^\s*//g; s/\s\s*/\t/g;' | \
        grep -w "^$1" | \
        cut -f2
    }
    pstree() {
        for pid in $@; do
            echo $pid
            for child in $(pschildren $pid); do
                pstree $child
            done
        done
    }
    killtree() {
        kill -9 $(
            { set +x; } 2>/dev/null;
            pstree $@;
            set -x;
        ) 2>/dev/null
    }
    getshims() {
        ps -e -o pid= -o args= ps -e -o pid= -o args= | grep -w 'containerd[-]shim' | cut -d ' ' -f 1
    }
    killtree $(getshims) || true

- name: k3s | umount
  become: true
  shell: |
    do_unmount() {
        { set +x; } 2>/dev/null
        MOUNTS=
        while read ignore mount ignore; do
            MOUNTS="$mount\n$MOUNTS"
        done </proc/self/mounts
        MOUNTS=$(printf $MOUNTS | grep "^$1" | sort -r)
        if [ -n "${MOUNTS}" ]; then
            set -x
            umount ${MOUNTS}
        else
            set -x
        fi
    }
    do_unmount '/run/k3s'
    do_unmount '/var/lib/rancher/k3s'
    do_unmount '/var/lib/kubelet/pods'
    do_unmount '/run/netns/cni-'

- name: k3s | clean network
  become: true
  shell: |
    # Delete network interface(s) that match 'master cni0'
    ip link show 2>/dev/null | grep 'master cni0' | while read ignore iface ignore; do
        iface=${iface%%@*}
        [ -z "$iface" ] || ip link delete $iface
    done
    ip link delete cni0
    ip link delete flannel.1
    rm -rf /var/lib/cni/
    iptables-save | grep -v KUBE- | grep -v CNI- | iptables-restore
# 默认不会删除 10.42.0.0/16 路由
# grep -v '10[.]42[.]0[.]0/16' |
