
- name: detech aarch64 arch
  set_fact:
    k3s_arch: arm64
  when: k3s_arch is undefined and ansible_architecture == 'aarch64'

- name: detech armhf arch
  set_fact:
    k3s_arch: armhf
  when: k3s_arch is undefined and ansible_architecture == 'armhf'

- name: detech x86_64 arch
  set_fact:
    k3s_arch: amd64
  when: k3s_arch is undefined and ansible_architecture == 'x86_64'

- name: fetch latest version
  delegate_to: localhost
  shell: curl -sfL https://api.github.com/repos/rancher/k3s/releases/latest | jq .tag_name -r
  register: shell
  # warn: false
  changed_when: false
  when: k3s_version is undefined

- name: set version
  set_fact:
    k3s_version: "{{k3s_version|default(shell.stdout)}}"
    k3s_arch: "{{k3s_arch|default('amd64')}}"
    k3s_release_url: "{{k3s_release_url|default('https://github.com/rancher/k3s/releases/download')}}"

- name: set k3s facts
  set_fact:
    k3s_download_url: "{{k3s_download_url|default(k3s_release_url+'/'+k3s_version)}}"
    k3s_local_path: "files/k3s/{{k3s_version}}/{{k3s_arch}}"

- name: report
  debug:
    msg: "K3S {{k3s_arch}} {{k3s_version}}"
