- import_tasks: k3s-preset.yaml

- import_tasks: docker-service.yaml

- name: prepare install dir
  become: true
  file:
    owner: admin
    path: /opt/k3s
    state: directory

# - name: ensure rsync
#   become: true
#   package:
#     name: rsync
#     state: present

- name: send
  copy:
    src: "{{k3s_local_path}}/"
    dest: "/opt/k3s/"

# - name: chmod
#   become: true
#   file:
#     path: /opt/k3s/{{item}}
#     mode: +x
#   loop:
#   - k3s

- name: install k3s
  become: true
  synchronize:
    src: /opt/k3s/k3s
    dest: /usr/local/bin
  delegate_to: "{{ inventory_hostname }}"

- name: k3s +x
  become: true
  file:
    dest: /usr/local/bin/k3s
    mode: a+x

# - name: create soft link
#   become: true
#   file:
#     src: /usr/local/bin/k3s
#     dest: /usr/local/bin/{{item}}
#     state: link
#     # mode: +x
#   loop:
#   - kubectl
#   - crictl
#   - ctr

- name: install
  become: true
  command: >
    env
    INSTALL_K3S_SKIP_DOWNLOAD=true
    INSTALL_K3S_SKIP_ENABLE=true
    INSTALL_K3S_VERSION={{k3s_version}}

    {{k3s_install_env|default('')}}

    /opt/k3s/k3s-install.sh
    {{k3s_install_options|default('')}}
