- name: install pdns-recursor packages
  become: true
  apk:
    name: "{{item}}"
  loop:
  - pdns-recursor
  - pdns-recursor-openrc

- name: "check conf exists {{pdns_recursor_conf_path}}"
  delegate_to: localhost
  stat:
    path: "{{pdns_recursor_conf_path}}"
  register: stat_result
- name: copy recursor.conf
  become: true
  copy:
    dest: /etc/pdns/recursor.conf
    src: "{{pdns_recursor_conf_path}}"
  when: stat_result.stat.exists
  notify: pdns-recursor-restart

- name: start pdns-recursor service
  become: true
  service:
    name: pdns-recursor
    state: started

- name: enable pdns-recursor service
  become: true
  service:
    name: pdns-recursor
    enabled: true
