- name: quagga install
  become: true
  apk:
    name: "{{item}}"
  loop:
  - quagga

- name: quagga log dir
  become: true
  file:
    path: /var/log/quagga
    state: directory
    owner: quagga

- name: sync configs
  include_tasks: quagga-conf-sync.yaml

- name: daemons service
  include_tasks: quagga-daemon-service.yaml
  vars:
    quagga_daemon: "{{item}}"
  loop:
  - zebra
  - ripd
  - ripngd
  - ospfd
  - ospf6d
  - bgpd
