- name: add rsync
  become: true
  apk:
    name: rsync

- name: detect local conf path
  include_tasks: service-conf-path.yaml

- name: sync {{nginx}} config
  become: true
  synchronize:
    src: "{{service_conf_path}}/"
    dest: "{{service_dest_conf_path}}/"
    recursive: true
  when: "service_conf_path | length > 0"
  notify: "{{service_name}}-reload"
