# orders:
# {{service_name}}_conf_path
# files/{{inventory_hostname}}/{{service_name}}
# files/{{service_name}}

- name: detect local conf path of {{service_name}} service
  set_fact:
    service_conf_path: "{{lookup('vars', service_name+'_conf_path') | default(lookup('first_found', ['files/'+inventory_hostname+'/'+service_name,'files/'+(working_group|default(''))+'/'+service_name,'files/'+service_name], errors='ignore'))}}"
- name: found path {{service_conf_path}}
  set_fact:
    services: "{{services | default({}) | combine({'{{service_name}}':{'local_conf_path':'{{service_conf_path}}'}}, recursive=True)}}"
  when: service_conf_path | length > 0
