- name: add rsync
  become: true
  apk:
    name: rsync

- name: detect local conf path
  include_tasks: service-conf-path.yaml

- name: sync {{service_name}} config dir
  become: true
  synchronize:
    src: "{{service_conf_path}}/"
    dest: "{{service_conf_dest_path}}/"
    recursive: true
    delete: "{{service_conf_delete|default(false)}}"
  when: "service_conf_path is directory"
  notify: "{{service_name}}-reload"

- name: sync {{service_name}} config file
  become: true
  synchronize:
    src: "{{service_conf_path}}"
    dest: "{{service_conf_dest_path}}"
  when: "service_conf_path is file"
  notify: "{{service_name}}-reload"
