# will not keep tzdata pkg after copy and link
- name: setup timezone
  become: true
  shell: setup-timezone -z Asia/Shanghai

# /etc/keymap - will not keep keymap pkg
# rc-update add loadkmap boot
- name: setup keymap
  become: true
  shell: setup-keymap us us

- name: setup ntp
  become: true
  service:
    # busybox->ntpd chronyd openntpd
    name: "{{ntp_service|default('ntpd')}}"
    enabled: true
    state: started
    runlevel: default

# poweroff or reset works
- name: enable acpid
  become: true
  service:
    name: acpid
    enabled: true
    state: started
    runlevel: default

# device hotplug
# - name: enable mdev when no udev
#   service:
#       name: mdev
#       enabled: true
#       state: started
#       runlevel: sysinit
