- name: install packages for ops
  become: true
  apk:
    name: "{{item}}"
  loop:
  - bash
  - bash-completion
  - tmux
  - mosh
  - file
  - tree
  - rsync
  - htop
  # info
  - neofetch
  - util-linux
  - util-linux-bash-completion
  # sshrc needs
  - vim
  - tar
  - coreutils
  - openssl

# common op service
# crond local
