- name: setup timezone
  become: true
  shell: setup-timezone -z Asia/Shanghai

- name: setup keymap
  become: true
  shell: setup-keymap us us

- name: setup ntp
  become: true
  shell: setup-ntp -c busybox
