- include_tasks: tinc-install.yaml

- include_tasks: tinc-preset.yaml

- name: check network exists
  shell: tinc network | grep '^{{tinc_netname}}$'
  register: shell_result
  failed_when: shell_result.rc == 0

# 如果网络名字相同 - 则直接跳过
# 如果网络名字不同 - 则中止或者从新配置

- name: check node exists
  become: true
  delegate_to: "{{tinc_master}}"
  environment:
    NETNAME: "{{tinc_netname}}"
  shell: "tinc info {{tinc_name}}"
  register: tinc_check_out
  changed_when: false
  failed_when: tinc_check_out.rc not in [ 0, 1 ]

- name: invite node to {{tinc_netname}}
  become: true
  delegate_to: "{{tinc_master}}"
  environment:
    NETNAME: "{{tinc_netname}}"
  shell: "tinc invite {{tinc_name}}"
  register: tinc_invite_out
  when: tinc_check_out.rc == 1

# - name: join url
#   debug:
#     msg: "{{tinc_invite_out.stdout}}"

- name: join tinc
  become: true
  shell: "tinc join {{tinc_invite_out.stdout}}"
  when: tinc_check_out.rc == 1
