- include_tasks: tinc-install.yaml
- include_tasks: tinc-preset.yaml

- name: check tinc net exists
  stat:
    path: "{{tinc_conf_dir}}"
  register: stat_result

- name: init tinc net
  become: true
  environment:
    NETNAME: "{{tinc_netname}}"
  shell: "tinc init {{tinc_name}}"
  when: not stat_result.stat.exists

- include_tasks: tinc-conf.yaml
- include_tasks: tinc-enable.yaml
