- include_tasks: tinc-preset.yaml

- name: stop tinc
  become: true
  environment:
    NETNAME: "{{tinc_netname}}"
  shell: tinc pid &>/dev/null && tinc stop && echo 1 || echo 0
  register: tinc_stop_out
  changed_when: tinc_stop_out.stdout == '1'
