- include_tasks: tinc-preset.yaml

- name: stop tinc
  become: true
  environment:
    NETNAME: "{{tinc_netname}}"
  shell: tinc pid &>/dev/null && tinc stop && echo 1 || echo 0
  register: tinc_stop_out
  changed_when: tinc_stop_out.stdout == '1'

- name: remove tinc.networks
  become: true
  lineinfile:
    path: /etc/conf.d/tinc.networks
    regex: 'NETWORK:\s*{{tinc_netname}}'
    state: absent

- name: remove tinc host conf
  become: true
  file:
    path: "{{tinc_conf_dir}}"
    state: absent

- name: check remaning network
  shell: tinc network | wc -l
  register: tinc_network_out
  changed_when: false

- name: disable tinc service
  become: true
  service:
    name: tincd
    state: stopped
    enabled: false
  when: tinc_network_out.stdout == '0'
