- name: tinc preset
  set_fact:
    # multi TINC detect tinc_$NETNAME_property
    # the master node used to invite nodes
    tinc_master: >-
      {{
      tinc_master
      |default(lookup('vars', 'tinc_'+tinc_netname+'_master',default=null))
      |default(tinc_netname)
      }}
    # name for node
    # tinc not allowed `-' in name but it's common in hostname
    tinc_name: "{{tinc_name|default(lookup('vars', 'tinc_'+tinc_netname+'_name',default=null))|default(inventory_hostname)|regex_replace('[-]','_')}}"
    # address for node
    tinc_address: "{{tinc_address|default(lookup('vars', 'tinc_'+tinc_netname+'_address',default=null))}}"
    # the whole subnet - not node subnet
    tinc_subnet: "{{tinc_subnet|default(lookup('vars', 'tinc_'+tinc_netname+'_subnet',default=null))}}"
    # kv conf for /etc/tinc/$NETNAME/tinc.conf
    tinc_conf: "{{tinc_conf|default(lookup('vars', 'tinc_'+tinc_netname+'_conf',default=[]))}}"
    # kv for /etc/tinc/$NETNAME/hosts/$NETNAME
    tinc_host_conf: "{{tinc_host_conf|default(lookup('vars', 'tinc_'+tinc_netname+'_host_conf',default=[]))}}"
    # conf dir to sync
    tinc_conf_dir: "{{tinc_conf_dir|default(lookup('vars', 'tinc_'+tinc_netname+'_conf_dir',default=null))|default('/etc/tinc/'+tinc_netname)}}"
    # custom          - do not genrate tinc-up - try sync
    # empty           - generate empty tinc-up
    # static-address  - generate tinc-up: ifconfig $INTERFACE {{tinc_address|ipaddr('address')}} netmask {{tinc_subnet|default(tinc_address)|ipaddr('netmask')}}
    # bridge          - generate tinc-up: ip li set $INTERFACE {{tinc_bridge_master}}; ip li set $INTERFACE up
    # dhcp            - TODO udhpc $INTERFACE
    tinc_interface_mode: >-
      {{
      tinc_interface_mode
      |default(lookup('vars', 'tinc_'+tinc_netname+'_interface_mode',default=null))
      |default('bridge' if lookup('vars','tinc_bridge_master',default='') != '' else null)
      |default('static-address')
      }}

    tinc_preset: true
  failed_when: tinc_netname is undefined
  when: 'not (tinc_preset|default(false))'
