- name: update tinc.networks
  become: true
  lineinfile:
    path: /etc/conf.d/tinc.networks
    line: 'NETWORK: {{tinc_netname}}'
    regex: '^[^#]*?{{tinc_netname}}'
  notify: tinc-restart
  when: tinc_netname is defined

- name: enable tinc service
  become: true
  service:
    name: tincd
    state: started
    enabled: true
