- include_tasks: tinc-preset.yaml

- name: apply tinc conf
  become: true
  template:
    path: "{{tinc_conf_dir}}/tinc.conf"
    line: '{{item.name}}={{item.value}}'
    regex: '^[^#]*?{{item.name}}(\s|=)'
    state: "{{item.state|default('present')}}"
  loop: "{{tinc_conf}}"
  when: tinc_conf is defined
  notify: "tinc-reload"

- name: apply host conf
  become: true
  lineinfile:
    path: "{{tinc_conf_dir}}/hosts/{{tinc_name}}"
    line: '{{item.name}}={{item.value}}'
    regex: '^[^#]*?{{item.name}}(\s|=)'
    state: "{{item.state|default('present')}}"
  loop: "{{tinc_host_conf}}"
  when: tinc_host_conf is defined
  notify: "tinc-reload"

- name: tinc-up conf
  become: true
  copy:
    dest: "{{tinc_conf_dir}}/tinc-up"
    content: |
      #!/bin/sh
      ifconfig $INTERFACE {{tinc_address|ipaddr('address')}} netmask {{tinc_subnet|default(tinc_address)|ipaddr('netmask')}}
  when: tinc_address is defined
  notify: "tinc-reload"
