- name: update tinc.networks
  become: true
  lineinfile:
    path: /etc/conf.d/tinc.networks
    line: 'NETWORK: {{tinc_netname}}'
    regex: '^[^#]*?{{tinc_netname}}'
  notify: tinc-restart
  when:
  - not ('/etc/init.d/tincd.{{tinc_netname}}' is file)

- name: enable tinc service
  become: true
  service:
    name: tincd
    state: started
    enabled: true
  when:
  - not ('/etc/init.d/tincd.{{tinc_netname}}' is file)

- include_tasks: tinc-service-disable.yaml
  when:
  - "'/etc/init.d/tincd.{{tinc_netname}}' is file"

- include_tasks: tinc-supervise-start.yaml
  when:
  - "'/etc/init.d/tincd.{{tinc_netname}}' is file"
