- name: install udev
  become: true
  apk:
    name: '{{item}}'
  loop:
  - eudev
  - udev-init-scripts

- name: enable udev on boot
  become: true
  service:
    name: '{{item}}'
    enabled: true
    runlevel: sysinit
  loop:
  - udev
  - udev-trigger

- name: start udev
  become: true
  service:
    name: '{{item}}'
    state: started
  loop:
  - udev
  - udev-trigger

- name: trigger udev
  command: udevadm trigger
  changed_when: no
