- name: mkdir credentials
  file:
    path: credentials
    state: directory

- name: generate admin_rsa.passwd
  file:
    path: credentials/admin_rsa.passwd
    content: "{{ lookup('password', 'credentials/admin_rsa.passwd chars=ascii_letters length=32') }}"
  when: "'credentials/admin_rsa.pub' is not file"

- name: generate admin_rsa
  shell: ssh-keygen -q -t rsa -N $(cat credentials/admin_rsa.passwd) -f credentials/admin_rsa
  when: "'credentials/admin_rsa.pub' is not file"

- name: generate admin_rsa_vault.passwd
  file:
    path: credentials/admin_rsa_vault.passwd
    content: "{{ lookup('password', 'credentials/admin_rsa_vault.passwd chars=ascii_letters length=32') }}"
  when: "'credentials/admin_rsa.pri' is not file"

- name: encrypt admin_rsa
  shell: ansible-vault encrypt credentials/admin_rsa --output=credentials/admin_rsa.pri --vault-password-file=credentials/admin_rsa_vault.passwd
  when: "'credentials/admin_rsa.pri' is not file"

- name: add .gitignore
  lineinfile:
    path: ./.gitignore
    line: '{{item}}'
    create: true
  loop:
  - '*.passwd'
  - '*_rsa'
